# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cert.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Certificates(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(380, 319)
        self.email_text = QtWidgets.QLabel(Dialog)
        self.email_text.setGeometry(QtCore.QRect(20, 24, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.email_text.setFont(font)
        self.email_text.setObjectName("email_text")
        self.fio_text = QtWidgets.QLabel(Dialog)
        self.fio_text.setGeometry(QtCore.QRect(20, 80, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fio_text.setFont(font)
        self.fio_text.setObjectName("fio_text")
        self.email = QtWidgets.QLineEdit(Dialog)
        self.email.setGeometry(QtCore.QRect(20, 50, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.fio = QtWidgets.QLineEdit(Dialog)
        self.fio.setGeometry(QtCore.QRect(20, 110, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fio.setFont(font)
        self.fio.setObjectName("fio")
        self.OK = QtWidgets.QPushButton(Dialog)
        self.OK.setGeometry(QtCore.QRect(290, 170, 81, 101))
        self.OK.setObjectName("OK")
        self.res = QtWidgets.QLabel(Dialog)
        self.res.setGeometry(QtCore.QRect(20, 280, 261, 31))
        self.res.setText("")
        self.res.setObjectName("res")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(20, 170, 261, 101))
        self.textEdit.setObjectName("textEdit")
        self.fio_text_2 = QtWidgets.QLabel(Dialog)
        self.fio_text_2.setGeometry(QtCore.QRect(20, 140, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fio_text_2.setFont(font)
        self.fio_text_2.setObjectName("fio_text_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.email_text.setText(_translate("Dialog", "Email"))
        self.fio_text.setText(_translate("Dialog", "ФИО"))
        self.OK.setText(_translate("Dialog", "Отправить"))
        self.fio_text_2.setText(_translate("Dialog", "Комментарии:"))
