# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cert_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(597, 333)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 571, 281))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 541, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.label_3.setObjectName("label_3")
        self.email = QtWidgets.QLineEdit(self.groupBox_2)
        self.email.setGeometry(QtCore.QRect(10, 40, 521, 20))
        self.email.setObjectName("email")
        self.fio = QtWidgets.QLineEdit(self.groupBox_2)
        self.fio.setGeometry(QtCore.QRect(10, 90, 521, 20))
        self.fio.setText("")
        self.fio.setObjectName("fio")
        self.OK = QtWidgets.QPushButton(self.groupBox)
        self.OK.setGeometry(QtCore.QRect(20, 240, 151, 23))
        self.OK.setObjectName("OK")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 130, 151, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.c350 = QtWidgets.QRadioButton(self.groupBox_3)
        self.c350.setGeometry(QtCore.QRect(10, 40, 121, 20))
        self.c350.setObjectName("c350")
        self.c100 = QtWidgets.QRadioButton(self.groupBox_3)
        self.c100.setGeometry(QtCore.QRect(10, 20, 121, 20))
        self.c100.setChecked(True)
        self.c100.setObjectName("c100")
        self.c500 = QtWidgets.QRadioButton(self.groupBox_3)
        self.c500.setGeometry(QtCore.QRect(10, 60, 121, 20))
        self.c500.setObjectName("c500")
        self.c750 = QtWidgets.QRadioButton(self.groupBox_3)
        self.c750.setGeometry(QtCore.QRect(10, 80, 121, 20))
        self.c750.setObjectName("c750")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(180, 130, 381, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 361, 71))
        self.textEdit.setObjectName("textEdit")
        self.res = QtWidgets.QLabel(self.groupBox_4)
        self.res.setGeometry(QtCore.QRect(10, 100, 361, 16))
        self.res.setText("")
        self.res.setObjectName("res")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 597, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Отримувач"))
        self.label_2.setText(_translate("MainWindow", "Email"))
        self.label_3.setText(_translate("MainWindow", "ФІО"))
        self.OK.setText(_translate("MainWindow", "Надіслати"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Оберіть сертифікат"))
        self.c350.setText(_translate("MainWindow", "Сертифікат - 350"))
        self.c100.setText(_translate("MainWindow", "Сертифікат - 100"))
        self.c500.setText(_translate("MainWindow", "Сертифікат - 500"))
        self.c750.setText(_translate("MainWindow", "Сертифікат - 750"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Коментарі"))
